### ISSUE TITLE
[APF Odisha] Fix rule failure for Individual subject summary rule

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#103]
## Context
Subject summary rules (rule UUID ec69af69-8fd2-40b3-b429-025504c18a01) for Individual subject type are failing in this project for quite a while. This will lead to the subject summary not being shown to the user.
Reference: https://reporting.avniproject.org/question/542-rule-failure-telemetry?organisation=APF%20Odisha&organisation=APF%20Odisha%20UAT&rule_uuid=ec69af69-8fd2-40b3-b429-025504c18a01

## Acceptance Criteria
1. All rule failures related to rule uuid : ec69af69-8fd2-40b3-b429-025504c18a01 should be closed
2. The Metabase report above should report 0 errors
3. Subject summary should show up for the sample individuals

Analysis Tasks
1. Currently rule failure telemetry is reporting issues only from production. Check whether this is happening on UAT also
2. If this happening only on production then check if this is a data issue or code issue. 
3. Based on this decide the tech approach for this card. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzVRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07c236a7762317244b4a341ea768714cbdbd01e9/Screenshot%202023-10-19%20at%2010.55.12%20AM.png)

**Comment by vedfordev** [comment]
### Developer Note


### Analysis :

#### Problem :
1. The main cause of rule failing is due to **individual.getObservationReadableValue('High risk')[0]**.Because I find that in prod High risk is missing for individual.As per rule, we are showing summary if high risk is yes.
```
set role apfodisha;

select id from subject_type where name = 'Individual' and is_voided = false;

select * from public.individual where observations->'be0ab05f-b0f3-43ec-b598-fdde0679104a' isnull
and subject_type_id = (select id from subject_type where name = 'Individual' and is_voided = false)
;
```
2. As per individual decision rule, individual



#### Solution:
1. I changed the logic as below. And if individual will not have high risk in future it will not fail.
```
//SAMPLE RULE EXAMPLE
'use strict';
({params, imports}) =>  {
  const {summaries, individual} = params;
    if(individual.getObservationReadableValue('High risk') && individual.getObservationReadableValue('High risk')[0] == 'Yes'){
        const highrisk =  individual.findObservation('High risk');
        summaries.push({name: 'High risk', value: highrisk.getValue()});
    }
  return summaries;
};
```
2. Fix data in prod.


#### Reproduce and fix:
1. Register individual sync
2. Remove **High Risk** from back end
3. try to check summary
4. check rule failure telemetry

**Comment by vedfordev** [comment]
@nupoorkhandelwal 
This card is depends on card https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/102
