### ISSUE TITLE
APF Prod Bug fixes - Batch 2: Growth Monitoring visit for the beneficiary is showing incorrect

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#347]
- [ ]  Changes to be done in APF Odisha New UAT environment
- [ ]  The growth monitoring visit for the beneficiary is showing as 1st May 2023 instead of 1st July 2024. The last visit was completed on 16th June 2024, and the next visit is scheduled for 1st January 2023. The Poshan Sathi user has canceled 2-3 visits, and now it's showing May 2023.

User Id : 6371547207@apfodisha 
Role : Poshan Sathi
Beneficiary name : Kuladipa Behera

https://drive.google.com/open?id=1VweDD0O5SRN3GTBjHJTwMimlTagthunI

**Comment by nupoorkhandelwal** [comment]
This is a corner case scenario, this user had edited enrolment post our changes went live. As per logic under Enrolment, if there is no visit of type "Growth Monitoring", it will schedule it for the next month from the enrolment, ie. 1-Feb 2023 since enrolment date is 22 Jan 2023. 

Ideally, user should have completed or cancelled whatever  Child Followup visit was there and that would have generated the correct Growth Monitoring visit.ie, for July

Right now we cannot fix this, he will have to manually cancel visits till it reaches the month/year where the data entry needs to be done.
