### ISSUE TITLE
APF Odisha Phase 2: QRT child form showing as scheduled visit but when filled shows overdue validation error

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#444]
- [x] Changes to be made in APF UAT first
- [x] QRT users are unable to fill out the QRT child form which shows as scheduled visit but while filling it shows the overdue validation error

Beneficiary name : Baidanath Bhoi (https://drive.google.com/file/d/11R0WjWrlr_2Z60BvxYONwflCkahl1dkE/view?usp=sharing)

Bug Log:
https://docs.google.com/spreadsheets/d/1IlQJZDRw4rnuEHvO9HGJvvIQ6wPrXuGH8PdksUHYbm0/edit?gid=0#gid=0&range=A38:A49

**Comment by nupoorkhandelwal** [comment]
Checked this, and the issue is - The Validation checks for the overdue date and if it is same as today then also it will throw the error. While ideally user should be able to fill the form even if the overdue date and today's date is same, it should throw validation from next day onward of the overdue date.

To fix this, update the validation rule to-

const isMaxVisitDateTimeGreaterThanToday = moment(programEncounter.maxVisitDateTime).isBefore(moment(), 'day');

which is currently using - isSameOrBefore

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal @AnjaliBhagabati @dinesh2096 


**I have made the changes in the following forms:**

1. ANC
2. QRT PW
3. PW Home Visit
4. Child Home Visit
5. QRT Child
6. Training Completion

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1ABJZfPA5VOWB_BgCErxyDBvz7neZdUfX/view?usp=drive_link)
